### ISSUE TITLE
Use nested css classes

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/POL-POM-5#794]
Now that we can use less files instead of css files I think it's a good idea to use a nested css class hierarchy instead of a flat one.

For example, currently we have these css classes:
```css
.rightPane .miniatureList {
    -fx-pref-width: 53.5em;
    -fx-background-color: #FFFFFF;
    -fx-border-width: 0;
    -fx-border-style: none;
    -fx-padding: 0.5em;
}

.miniatureListElement {
    -fx-pref-width: 12em;
    -fx-pref-height: 9em;
    -fx-font-family: "Roboto Light";
    -fx-alignment: top-center;
    -fx-spacing: 0.3em;
    -fx-padding: 0.5em;
    -fx-cursor: hand;
    -fx-background-radius: 0.8em;
}

.miniatureListElement:hover {
    -fx-background-color: #EFEFEF;
}

.miniatureListElement.selected {
    -fx-background-color: #EAEAEA;
}

.miniatureImage {
    -fx-border-radius: 0.4em;
    -fx-background-radius: 0.4em;
    -fx-background-size: contain;
    -fx-background-repeat: no-repeat;
    -fx-background-position: center;
    -fx-pref-width: 15em;
    -fx-pref-height: 12em;
}

.miniatureText {
    -fx-font-size: 0.90em;
    -fx-wrap-text: true;
    -fx-alignment: center;
    -fx-text-alignment: center;
}
```

To make it better readable, and show how these elements are nested, I propose to use:
```less
.rightPane .miniatureList {
    -fx-pref-width: 53.5em;
    -fx-background-color: #FFFFFF;
    -fx-border-width: 0;
    -fx-border-style: none;
    -fx-padding: 0.5em;

    .miniatureListElement {
        -fx-pref-width: 12em;
        -fx-pref-height: 9em;
        -fx-font-family: "Roboto Light";
        -fx-alignment: top-center;
        -fx-spacing: 0.3em;
        -fx-padding: 0.5em;
        -fx-cursor: hand;
        -fx-background-radius: 0.8em;

        .miniatureImage {
            -fx-border-radius: 0.4em;
            -fx-background-radius: 0.4em;
            -fx-background-size: contain;
            -fx-background-repeat: no-repeat;
            -fx-background-position: center;
            -fx-pref-width: 15em;
            -fx-pref-height: 12em;
        }

        .miniatureText {
            -fx-font-size: 0.90em;
            -fx-wrap-text: true;
            -fx-alignment: center;
            -fx-text-alignment: center;
        }
    }

    .miniatureListElement:hover {
        -fx-background-color: #EFEFEF;
    }

    .miniatureListElement.selected {
        -fx-background-color: #EAEAEA;
    }
}
```
